# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: 127.0.0.1:1234:liquid/lfm2.5-1.2b
clients:
- type: openai-compatible
  name: 127.0.0.1:1234
  api_base: http://127.0.0.1:1234
  api_key: lmstudio
  models:
  - name: liquid/lfm2.5-1.2b
